---

- name: Install redis
  ansible.builtin.dnf:
    name:
      - redis
    state: installed

- name: Enable redis service
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true

- name: Copy redis configuration
  ansible.builtin.template:
    src: valkey.conf
    dest: /etc/valkey/valkey.conf
    mode: '0640'
  notify:
    - restart redis
