- name: Ensure pip3 is installed
  ansible.builtin.dnf:
    name: python3-pip
    state: installed

- name: Install python dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - pexpect
      - cryptography
