---

- name: Add mongo yum repository
  ansible.builtin.yum_repository:
    name: mongodb-org-8.0
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/8.0/x86_64/
    gpgcheck: true
    enabled: true
    gpgkey: https://pgp.mongodb.com/server-8.0.asc

- name: Install MongoDB packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mongodb-mongosh-shared-openssl3
    - mongodb-org-database
    - mongodb-org-server

- name: Install python dependencies
  ansible.builtin.pip:
    name:
      - pymongo

- name: Enable mongod service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true

- name: Copy mongo configuration
  ansible.builtin.template:
    src: mongo.conf
    dest: /etc/mongod.conf
    mode: '0644'
  changed_when: true
  notify:
    - restart mongod

- name: Disable auth
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '^\s*authorization:.*$'
    replace: '  authorization: "disabled"'

- name: Restart mongod
  ansible.builtin.service:
    name: mongod
    state: restarted

- name: Create {{ mongo_user }} user
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongo_user }}"
    password: "{{ mongo_password }}"
    roles:
      - role: root
        db: admin
    state: present

- name: Enable auth
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '^\s*authorization:.*$'
    replace: '  authorization: "enabled"'
  notify:
    - restart mongod
